// <auto-generated />
using System;
using InvestmentManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestmentManagement.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602173605_AddReturnedBookingStatus")]
    partial class AddReturnedBookingStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedShares")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("InvestorId", "Status");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableShares")
                        .HasColumnType("integer");

                    b.Property<string>("BKashTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MinInvestmentThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("PricePerShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalShares")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.CompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DocumentationUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CompanyProfiles", (string)null);
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BKashNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BKashNumber = "01700000000",
                            Email = "admin@investment.local",
                            PasswordHash = "AQAAAAIAAYagAAAAEOMOKl5MELwHbw57qyzQXyhK3yJUIP/CflvMivG0WKV8D9ZeCDjCrVQR62sHhylLdA==",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.Booking", b =>
                {
                    b.HasOne("InvestmentManagement.Api.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Bookings")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentManagement.Api.Domain.Entities.User", "Investor")
                        .WithMany("Bookings")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.Campaign", b =>
                {
                    b.HasOne("InvestmentManagement.Api.Domain.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany("Campaigns")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.CompanyProfile", b =>
                {
                    b.HasOne("InvestmentManagement.Api.Domain.Entities.User", "User")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("InvestmentManagement.Api.Domain.Entities.CompanyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.CompanyProfile", b =>
                {
                    b.Navigation("Campaigns");
                });

            modelBuilder.Entity("InvestmentManagement.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CompanyProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
